version: '3'
services: 
  api: 
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api
    # command: sh -c "sleep 1100"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=db_shopper
      - DB_PORT=3306
      - DB_DRIVER=mysql
    ports:
      - 5001:3000
    depends_on:
      mysql:
        condition: service_healthy
    deploy:
      resources:
        limits: 
          cpus: '0.3'
          memory: '300MB'
    networks:
      - network-node
      
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_shopper
    ports:
      - "3306:3306"  # Map host port to container port
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5GB'
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$root' ]
      timeout: 20s
      retries: 10
    networks:
      - network-node

networks:
  network-node:
    name: network-node


      